### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by jdblischak** [bogdanlab/h2gene#7]
Could you please tag a release? This is required for creating a conda package from a GitHub repository. You can copy-paste the following Git commands to create a new tag and push it to GitHub:

```
git pull origin main
git tag -a 0.1.2 -m "0.1.2"
git push origin --tags
```

The `-m` stands for "message", so you can write more there if you like.

**Comment by KangchengHou** [comment]
thanks and done

**Comment by jdblischak** [comment]
Thanks! I created a conda binary for 0.1.2. Conda users can install it from my channel:

```
conda install -c conda-forge -c jdblischak r-h2geneR
```

https://anaconda.org/jdblischak/r-h2gener/files?version=0.1.2
